export const platsLinks = [
  {
    name: "Google Podcast",
    url: "https://bit.ly/3QiAwf6",
    width: "196px",
    height: "196px",
    widthIcon: "98px",
    heightIcon: "98px",
    fontSize: "2rem",
    fontWeight: "normal",
  },
  {
    colorHoverText: "green",
    name: "Spotify",
    url: "https://spoti.fi/3QbrMHI",
    width: "274px",
    height: "274px",
    widthHover: "288px",
    heightHover: "288px",
    widthIcon: "136px",
    heightIcon: "136px",
    widthHoverDiv: "146px",
    heightHoverDiv: "146px",
    backColor: "green",
    fontSize: "2.8rem",
    fontWeight: "600",
  },
  {
    name: "Pocket Casts",
    url: "https://bit.ly/3PgAZ0e",
    width: "196px",
    height: "196px",
    widthIcon: "98px",
    heightIcon: "98px",
    fontSize: "2rem",
    fontWeight: "normal",
  },
];
